# Generated by Django 6.1.1 on 2026-09-30 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('purchasing', '0001_initial'),
        ('tasks', '0002_tasklink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='purchasing.part'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='moved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='related_purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='purchasing.purchaseorder'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='related_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stockitem'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(condition=models.Q(('quantity_available__lte', models.F('min_threshold'))), fields=['part'], name='idx_stock_item_low_stock'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_available__gte', 0)), name='ck_stock_item_qty_available'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.CheckConstraint(condition=models.Q(('min_threshold__gte', 0)), name='ck_stock_item_min_threshold'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['moved_at'], name='idx_stock_movement_moved_at'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movement_type', 'adjustment'), models.Q(('quantity', 0), _negated=True)), models.Q(models.Q(('movement_type', 'adjustment'), _negated=True), ('quantity__gt', 0)), _connector='OR'), name='ck_stock_movement_quantity'),
        ),
    ]
