# Generated by Django 6.1.1 on 2026-09-30 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subsystems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'year'), name='uq_competition_edition_name_year')],
            },
        ),
        migrations.CreateModel(
            name='TelemetrySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('session_type', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition_edition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='telemetry.competitionedition')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='telemetry_sessions', to=settings.AUTH_USER_MODEL)),
                ('subsystem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='telemetry_sessions', to='subsystems.subsystem')),
            ],
        ),
        migrations.CreateModel(
            name='TelemetryDataPoint',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp_ms', models.BigIntegerField()),
                ('sensor_name', models.CharField(max_length=150)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('telemetry_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='telemetry.telemetrysession')),
            ],
        ),
        migrations.AddIndex(
            model_name='telemetrysession',
            index=models.Index(fields=['session_date'], name='idx_telemetry_session_date'),
        ),
        migrations.AddIndex(
            model_name='telemetrydatapoint',
            index=models.Index(fields=['telemetry_session', 'sensor_name', 'timestamp_ms'], name='idx_telemetry_dp_sess_sens_t'),
        ),
    ]
