# Generated by Django 6.1.1 on 2026-09-30 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0008_member_facebook_url'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LifecycleStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=150)),
                ('applies_to_ic', models.BooleanField(default=True)),
                ('applies_to_ev', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['step_order'],
            },
        ),
        migrations.CreateModel(
            name='Subsystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('blocked', 'Blocked'), ('complete', 'Complete')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subsystems', to='members.orgunit')),
                ('parent_subsystem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='subsystems.subsystem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subsystems', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='MemberSubsystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_level', models.CharField(choices=[('main', 'Main'), ('junior', 'Junior')], max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subsystem_assignments', to=settings.AUTH_USER_MODEL)),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_assignments', to='subsystems.subsystem')),
            ],
        ),
        migrations.CreateModel(
            name='SubsystemStepProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lifecycle_step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_rows', to='subsystems.lifecyclestep')),
                ('subsystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_progress', to='subsystems.subsystem')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validated_steps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='subsystem',
            constraint=models.CheckConstraint(condition=models.Q(('parent_subsystem', models.F('id')), _negated=True), name='ck_subsystem_not_own_parent'),
        ),
        migrations.AddConstraint(
            model_name='membersubsystem',
            constraint=models.UniqueConstraint(fields=('subsystem', 'member', 'start_date'), name='uq_membersubsystem_subsystem_member_start'),
        ),
        migrations.AddConstraint(
            model_name='membersubsystem',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('start_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='ck_membersubsystem_dates'),
        ),
        migrations.AddConstraint(
            model_name='subsystemstepprogress',
            constraint=models.UniqueConstraint(fields=('subsystem', 'lifecycle_step'), name='uq_substep_progress_subsystem_step'),
        ),
    ]
