# Generated by Django 6.1.1 on 2026-09-30 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('purchasing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='purchasing.invoice'),
        ),
        migrations.AddField(
            model_name='expense',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='purchasing.purchaseorder'),
        ),
        migrations.AddField(
            model_name='expense',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='managed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sponsorships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('org_unit', 'fiscal_year'), name='uq_budget_org_unit_year'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.CheckConstraint(condition=models.Q(('allocated_amount__gte', 0)), name='ck_budget_allocated_amount'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['recorded_at'], name='idx_expense_recorded_at'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='ck_expense_amount'),
        ),
        migrations.AddIndex(
            model_name='sponsorship',
            index=models.Index(fields=['status'], name='idx_sponsorship_status'),
        ),
        migrations.AddConstraint(
            model_name='sponsorship',
            constraint=models.CheckConstraint(condition=models.Q(('amount__isnull', True), ('amount__gte', 0), _connector='OR'), name='ck_sponsorship_amount'),
        ),
    ]
