# Generated by Django 6.1.1 on 2026-09-30 12:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0009_membership_subsystem'),
        ('subsystems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('brakes', 'Brakes'), ('wheels_tyres', 'Wheels & tyres'), ('chassis_body', 'Chassis & body'), ('suspension', 'Suspension'), ('steering', 'Steering'), ('drivetrain', 'Drivetrain'), ('engine_tractive', 'Engine / tractive'), ('workshop', 'Workshop'), ('low_voltage', 'Low voltage'), ('operations', 'Operations'), ('other', 'Other')], default='other', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=150)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('material', models.CharField(blank=True, max_length=150)),
                ('process', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='members.orgunit')),
                ('subsystem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='subsystems.subsystem')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('priority', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, null=True)),
                ('requested_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('a_commander', 'To order'), ('en_commande', 'Ordered'), ('livre', 'Delivered'), ('annule', 'Cancelled')], default='a_commander', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='purchasing.part')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=150)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contacted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipping_addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, choices=[('fournisseur', 'Supplier'), ('sous_traitant', 'Subcontractor'), ('mixte', 'Mixed'), ('usinage', 'Machining'), ('logistique', 'Logistics')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('validee', 'Approved'), ('en_attente', 'Pending'), ('refusee', 'Refused'), ('pas_encore_envoyee', 'Not sent yet')], default='pas_encore_envoyee', max_length=20)),
                ('technical_capabilities', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=150)),
                ('country', models.CharField(blank=True, max_length=150)),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('contact_role', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('average_lead_time_days', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contacted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suppliers_contacted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('customs_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ordered_at', models.DateField(blank=True, null=True)),
                ('estimated_delivery_date', models.DateField(blank=True, null=True)),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('a_commander', 'To order'), ('en_commande', 'Ordered'), ('livre', 'Delivered'), ('annule', 'Cancelled')], default='en_commande', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='purchasing.purchaserequest')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='purchasing.shippingaddress')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='purchasing.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=150)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('issued_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='purchasing.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='purchasing.invoice')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_invoice_line_quantity'), models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='ck_invoice_line_unit_price'), models.CheckConstraint(condition=models.Q(('total_price__gte', 0)), name='ck_invoice_line_total_price')],
            },
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['category'], name='idx_part_category'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['reference'], name='idx_part_reference'),
        ),
        migrations.AddConstraint(
            model_name='part',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__isnull', True), ('quantity__gte', 0), _connector='OR'), name='ck_part_quantity'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['status'], name='idx_purchase_request_status'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequest',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_purchase_request_quantity'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['name'], name='idx_supplier_name'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['status'], name='idx_supplier_status'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['type'], name='idx_supplier_type'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.CheckConstraint(condition=models.Q(('average_lead_time_days__isnull', True), ('average_lead_time_days__gte', 0), _connector='OR'), name='ck_supplier_lead_time'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status'], name='idx_purchase_order_status'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__isnull', True), ('unit_price__gte', 0), _connector='OR'), name='ck_po_unit_price'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(condition=models.Q(('delivery_cost__gte', 0)), name='ck_po_delivery_cost'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(condition=models.Q(('customs_cost__gte', 0)), name='ck_po_customs_cost'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(condition=models.Q(('total_price__isnull', True), ('total_price__gte', 0), _connector='OR'), name='ck_po_total_price'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_delivery_date__isnull', True), ('ordered_at__isnull', True), ('estimated_delivery_date__gte', models.F('ordered_at')), _connector='OR'), name='ck_po_estimated_date'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(condition=models.Q(('actual_delivery_date__isnull', True), ('ordered_at__isnull', True), ('actual_delivery_date__gte', models.F('ordered_at')), _connector='OR'), name='ck_po_actual_date'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['issued_at'], name='idx_invoice_issued_at'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('supplier', 'reference'), name='uq_invoice_supplier_reference'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='ck_invoice_total_amount'),
        ),
    ]
