# Generated by Django 6.1.1 on 2026-09-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgunit',
            name='code',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='role',
            name='code',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
