# Generated by Django 6.1.1 on 2026-09-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_orgunit_code_role_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='in_executive_bureau',
            field=models.BooleanField(default=False),
        ),
    ]
