# Generated by Django 6.1.1 on 2026-09-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_role_in_executive_bureau'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_auto',
            field=models.BooleanField(default=False),
        ),
    ]
