# Generated by Django 6.1.1 on 2026-09-21 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_membership_is_auto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='in_executive_bureau',
        ),
    ]
