# Generated by Django 6.1.1 on 2026-09-21 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_remove_role_in_executive_bureau'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='is_auto',
        ),
    ]
