# Generated by Django 6.1.1 on 2026-09-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_remove_membership_is_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='code',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
