# Generated by Django 6.1.1 on 2026-09-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_member_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
