# Generated by Django 6.1.1 on 2026-09-30 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_member_facebook_url'),
        ('subsystems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='subsystem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='subsystems.subsystem'),
        ),
    ]
